[package]
name = "bakery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.2"
#clap_autocomplete = "0.4.1"
#env_logger = "0.10.0"
#log = "0.4.20"

