name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  buildntest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup build env
      run: make setup-rust
    
    - name: Build musl x86_64
      run:  cargo build --target x86_64-unknown-linux-musl --release
    
    - name: Build glibc x86_64
      run: cargo build --verbose
    
    - name: Run tests
      run: cargo test --verbose
