name: Build and Publish Docker Image

on:
  workflow_dispatch:  # Allows manual trigger from the GitHub Actions tab
    inputs:
      tag_name:
        description: 'Tag name for the release (e.g., v0.1.43)'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get Tag
      run: |
        if [[ -n "${{ github.event.inputs.tag_name }}" ]]; then
          CURRENT_TAG=${{ github.event.inputs.tag_name }}
        else
          CURRENT_TAG=${{ github.ref }}
          CURRENT_TAG=${CURRENT_TAG#refs/tags/}  # Strip off 'refs/tags/' prefix
        fi
        echo "CURRENT_TAG=${CURRENT_TAG}" >> "$GITHUB_ENV"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to ghcr.io
      uses: docker/login-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Docker namespace
      id: repository_name
      run: echo "DOCKER_NAMESPACE=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Extract Docker metadata (tags, labels)
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ env.DOCKER_NAMESPACE }}/bakery-workspace:${{ env.CURRENT_TAG }}

    - name: Package
      run: make deb-package

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        tags: ghcr.io/${{ env.DOCKER_NAMESPACE }}/bakery-workspace:${{ env.CURRENT_TAG }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Log out from GitHub Container Registry
      run: docker logout ghcr.io
