name: Release

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: make build
    - name: Tests
      run: make test
    - name: Release
      run: make release
    - name: Push 
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git push https://${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
